package com.friday.ai.core

import kotlin.math.cos
import kotlin.math.ln
import kotlin.math.max
import kotlin.math.min
import kotlin.math.sin

/**
 * Kaldi-compatible 80-bin log-mel filterbank.
 *
 * The speaker model was trained on features from
 * `torchaudio.compliance.kaldi.fbank`, and an embedding model is completely
 * unforgiving about its input: features that are merely *close* do not give
 * slightly worse embeddings, they give meaningless ones, silently. So this is
 * a deliberate port of that function rather than a generic mel spectrogram,
 * down to the details that are easy to get wrong:
 *
 *  - the window is **hamming**, not Kaldi's own "povey" default, because
 *    that is what wespeaker trains with;
 *  - the hamming denominator is `N - 1`, not `N`;
 *  - DC removal happens before pre-emphasis, and pre-emphasis replicates the
 *    first sample rather than assuming a zero before it;
 *  - the FFT is padded to 512, and the mel triangles are built over 256 bins
 *    with a zero appended for Nyquist;
 *  - input is expected at **int16 scale** (±32768), not normalised to ±1.
 *
 * [KaldiFbankTest] pins the output against values generated by torchaudio
 * itself, so a drift in any of the above fails a test rather than quietly
 * degrading recognition.
 */
object KaldiFbank {

    const val SAMPLE_RATE = 16000
    const val NUM_MEL_BINS = 80

    private const val FRAME_LENGTH_MS = 25
    private const val FRAME_SHIFT_MS = 10
    const val FRAME_SIZE = SAMPLE_RATE / 1000 * FRAME_LENGTH_MS   // 400
    const val FRAME_SHIFT = SAMPLE_RATE / 1000 * FRAME_SHIFT_MS   // 160

    /** Next power of two at or above [FRAME_SIZE]. */
    private const val FFT_SIZE = 512
    private const val NUM_FFT_BINS = FFT_SIZE / 2                  // 256, Nyquist excluded

    private const val PREEMPHASIS = 0.97
    private const val LOW_FREQ = 20.0
    private const val HIGH_FREQ = SAMPLE_RATE / 2.0

    /** `torch.finfo(torch.float).eps`, the floor torchaudio takes the log of. */
    private const val EPSILON = 1.1920928955078125e-07

    private val window: DoubleArray = DoubleArray(FRAME_SIZE) { i ->
        // a = 2*pi/(N-1): the periodic-vs-symmetric distinction matters here.
        0.54 - 0.46 * cos(2.0 * Math.PI / (FRAME_SIZE - 1) * i)
    }

    /** [NUM_MEL_BINS] triangles over [NUM_FFT_BINS] power-spectrum bins. */
    private val melBanks: Array<DoubleArray> = buildMelBanks()

    /** How many frames [sampleCount] samples yield. Kaldi's `snip_edges=true`. */
    fun frameCount(sampleCount: Int): Int =
        if (sampleCount < FRAME_SIZE) 0 else 1 + (sampleCount - FRAME_SIZE) / FRAME_SHIFT

    /**
     * @param samples audio at 16 kHz, **int16 scale**
     * @return `[frames][80]` log-mel energies, row-major
     */
    fun compute(samples: FloatArray): Array<FloatArray> {
        val frames = frameCount(samples.size)
        if (frames == 0) return emptyArray()

        val re = DoubleArray(FFT_SIZE)
        val im = DoubleArray(FFT_SIZE)
        val frame = DoubleArray(FRAME_SIZE)
        val power = DoubleArray(NUM_FFT_BINS)

        return Array(frames) { f ->
            val offset = f * FRAME_SHIFT

            var sum = 0.0
            for (i in 0 until FRAME_SIZE) {
                frame[i] = samples[offset + i].toDouble()
                sum += frame[i]
            }
            val mean = sum / FRAME_SIZE
            for (i in 0 until FRAME_SIZE) frame[i] -= mean

            // Pre-emphasis, walking backwards so each sample still sees its
            // untouched predecessor. The first sample replicates itself.
            for (i in FRAME_SIZE - 1 downTo 1) {
                frame[i] -= PREEMPHASIS * frame[i - 1]
            }
            frame[0] -= PREEMPHASIS * frame[0]

            java.util.Arrays.fill(re, 0.0)
            java.util.Arrays.fill(im, 0.0)
            for (i in 0 until FRAME_SIZE) re[i] = frame[i] * window[i]

            fft(re, im)
            for (k in 0 until NUM_FFT_BINS) power[k] = re[k] * re[k] + im[k] * im[k]

            FloatArray(NUM_MEL_BINS) { b ->
                val bank = melBanks[b]
                var energy = 0.0
                for (k in 0 until NUM_FFT_BINS) {
                    if (bank[k] != 0.0) energy += bank[k] * power[k]
                }
                ln(max(energy, EPSILON)).toFloat()
            }
        }
    }

    /**
     * Cepstral mean normalisation, in place: subtract each bin's mean across
     * time. wespeaker applies this before the model, and skipping it shifts
     * every embedding by the recording's channel response.
     */
    fun subtractMean(features: Array<FloatArray>) {
        if (features.isEmpty()) return
        for (b in 0 until NUM_MEL_BINS) {
            var sum = 0.0
            for (frame in features) sum += frame[b]
            val mean = (sum / features.size).toFloat()
            for (frame in features) frame[b] -= mean
        }
    }

    private fun melScale(freq: Double): Double = 1127.0 * ln(1.0 + freq / 700.0)

    private fun buildMelBanks(): Array<DoubleArray> {
        val fftBinWidth = SAMPLE_RATE.toDouble() / FFT_SIZE
        val melLow = melScale(LOW_FREQ)
        val melHigh = melScale(HIGH_FREQ)
        val delta = (melHigh - melLow) / (NUM_MEL_BINS + 1)

        return Array(NUM_MEL_BINS) { b ->
            val left = melLow + b * delta
            val center = melLow + (b + 1) * delta
            val right = melLow + (b + 2) * delta
            DoubleArray(NUM_FFT_BINS) { k ->
                val mel = melScale(fftBinWidth * k)
                val up = (mel - left) / (center - left)
                val down = (right - mel) / (right - center)
                max(0.0, min(up, down))
            }
        }
    }

    /** In-place iterative radix-2 FFT. [re]/[im] must be [FFT_SIZE] long. */
    private fun fft(re: DoubleArray, im: DoubleArray) {
        val n = re.size
        var j = 0
        for (i in 1 until n) {
            var bit = n shr 1
            while (j and bit != 0) {
                j = j xor bit
                bit = bit shr 1
            }
            j = j or bit
            if (i < j) {
                var t = re[i]; re[i] = re[j]; re[j] = t
                t = im[i]; im[i] = im[j]; im[j] = t
            }
        }
        var len = 2
        while (len <= n) {
            val ang = -2.0 * Math.PI / len
            val wRe = cos(ang)
            val wIm = sin(ang)
            var i = 0
            while (i < n) {
                var curRe = 1.0
                var curIm = 0.0
                for (k in 0 until len / 2) {
                    val uRe = re[i + k]
                    val uIm = im[i + k]
                    val vRe = re[i + k + len / 2] * curRe - im[i + k + len / 2] * curIm
                    val vIm = re[i + k + len / 2] * curIm + im[i + k + len / 2] * curRe
                    re[i + k] = uRe + vRe
                    im[i + k] = uIm + vIm
                    re[i + k + len / 2] = uRe - vRe
                    im[i + k + len / 2] = uIm - vIm
                    val nextRe = curRe * wRe - curIm * wIm
                    curIm = curRe * wIm + curIm * wRe
                    curRe = nextRe
                }
                i += len
            }
            len = len shl 1
        }
    }
}
